// Generated by Wrangler on Sat May 18 2024 14:22:04 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types -e preview --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
}
